### PR TITLE
Added Shortcut, Labels and Tooltips - new Version 0.1.1

### LINKED ISSUE #2: Remesh resolution for sculpt resets in each frame with keymesh
[video](https://gitlab.com/pepe-school-land/keymesh/uploads/4d5946d9cbc16859d165dcf3731df390/2021-02-01_22-42-50.mp4)

### PR DESCRIPTION
**Pull request by aldrinmathew**
### Functionality
**Faster Workflows**: Added shortcut **`Ctrl Shift A`**, to add a Keyframe to the selected Mesh.

### Fixes

#2 Remesh Resolution reset - https://github.com/pablodp606/keymesh-addon/pull/3/commits/730b39df4f822de88433b2cb58905e8bf32f8ea6
#5 Sculpt mode settings reset - https://github.com/pablodp606/keymesh-addon/pull/3/commits/730b39df4f822de88433b2cb58905e8bf32f8ea6

### UI
- Added a label for the Keyframe Mesh button.
- Increased the height of the Keyframe Mesh button to make it distinct from other operators of the addon.
- Added tooltips for operators.

### Addon Details

- Changed the Documentation URL to the Vimeo video instead of the previous private youtube video that cannot be viewed.
- Added a description to the addon.

### Others

- Added a README file with links to the Documentation video of the addon.
- Bumped version number to 0.1.2 to make a new release for the addon.
- Added Addon features to the README.

### CODE REVIEW

**Comment by aldrinmathew** [comment]
I apologise for cloning the addon from Gitlab.
The Gitlab version was hosted as a ZIP so, contributions were not possible. I have mentioned the link to this repository in [AldrinMathew/keymesh](https://github.com/AldrinMathew/keymesh). I will mark that repository as deprecated soon. And I will be committing future contributions to this repository.

**Comment by JoelGodin** [comment]
I've tried this branch and think it is a good improvement.
I recommend merging it to master.

**Comment by aldrinmathew** [comment]
@JoelGodin
Thanks. *Pablo Dobarro* is busy with a lot of things. As I was informed by *Daniel Martinez Lara*, Pablo and him will put much time into developing the addon, in March. Till then, Pablo might not be able to respond to repo updates and requests.

I believe the best thing that we can do is wait. And I will be making further improvements to the addon in my fork. And I have found a serious bug while testing the addon.

**Comment by aldrinmathew** [comment]
Just fixed *Issue #2* and *Issue #5* that reset Voxel Size, Voxel Adaptivity and Symmetry Mirror options in the Sculpt Mode settings, every time the Keyframe Mesh operator was called.

**Pull request closed without merging**
